[package]
name = "table"
version = "0.1.0"
authors = ["Marcelo Mottalli <mottalli@yahoo.com>"]
build = "build.rs"

[dependencies]
capnp = "0.6.0"
libc = "0.2.6"

[build-dependencies]
capnpc = "0.6.0"
